# Generated by Django 5.2.6 on 2025-09-21 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('topwear', 'Top Wear'), ('bottomwear', 'Bottom Wear'), ('shoes', 'Shoes'), ('gloves', 'Gloves'), ('accessories', 'Accessories'), ('socks', 'Socks'), ('trainingequipment', 'Training Equipment'), ('ball', 'Ball'), ('bag', 'Bag')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(default='', max_length=10)),
                ('sold', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
