# Generated by Django 5.2.6 on 2025-09-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('topwear', 'Top Wear'), ('bottomwear', 'Bottom Wear'), ('shoes', 'Shoes'), ('gloves', 'Gloves'), ('accessories', 'Accessories'), ('socks', 'Socks'), ('trainingequipment', 'Training Equipment'), ('ball', 'Ball'), ('bag', 'Bag')], max_length=20),
        ),
    ]
